# Generated by Django 5.2.5 on 2025-08-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='normalUser',
            field=models.BooleanField(default=False),
        ),
    ]
