# Generated by Django 5.2.5 on 2025-08-11 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_normaluser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='normalUser',
        ),
    ]
