# Generated by Django 5.2.5 on 2025-08-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_normaluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='shopowner',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
