# Generated by Django 5.2.5 on 2025-10-05 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='shopowner',
            new_name='is_seller',
        ),
    ]
