# Generated by Django 5.2.5 on 2025-10-05 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_shopowner_user_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_buyer',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
