# Generated by Django 5.2.5 on 2025-08-12 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
