# Generated by Django 5.2.5 on 2025-08-21 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_products_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='herobackimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='img/')),
            ],
            options={
                'verbose_name': 'herobackimg',
                'verbose_name_plural': 'Hero image',
            },
        ),
    ]
