# Generated by Django 5.2.5 on 2025-08-21 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_herobackimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_image2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_image2', to='Products.product_image'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_image3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_image3', to='Products.product_image'),
        ),
    ]
