# Generated by Django 5.2.5 on 2025-08-22 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_products_product_image2_products_product_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prod_image', to='Products.product_image'),
        ),
    ]
