# Generated by Django 5.2.5 on 2025-08-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='items',
        ),
    ]
