# Generated by Django 5.2.5 on 2025-08-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_remove_payment_email_payment_channel_payment_paid_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='image',
            field=models.ImageField(null=True, upload_to='img/product_images/'),
        ),
    ]
