# Generated by Django 5.2.5 on 2025-08-23 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_alter_product_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='heroimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heroimage', to='Products.product_image')),
            ],
        ),
    ]
