# Generated by Django 5.2.5 on 2025-08-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_heroimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='Ishero',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='heroimage',
        ),
    ]
