# Generated by Django 5.2.5 on 2025-08-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_cart_items_purchased_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
