# Generated by Django 5.2.5 on 2025-10-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_remove_order_reference_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
