# Generated by Django 5.2.5 on 2025-10-06 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0019_orderitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='ordered_product', to='Products.products'),
        ),
    ]
