# Generated by Django 5.2.5 on 2025-10-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0021_alter_cart_items_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivery_pending', 'Delivery_Pending'), ('cancelled', 'Cancelled'), ('paid', 'Paid')], default='completed', max_length=20),
        ),
    ]
