# Generated by Django 5.2.5 on 2025-10-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0022_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivery_pending', 'Delivery_Pending'), ('cancelled', 'Cancelled'), ('delivered', 'Delivered'), ('paid', 'Paid')], default='completed', max_length=20),
        ),
    ]
