# Generated by Django 5.2.5 on 2025-10-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0023_orderitem_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('waiting_for_delivery', 'Waiting _For_Delivery')], default='waiting_for_delivery', max_length=20),
        ),
    ]
