# Generated by Django 5.2.5 on 2025-10-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0025_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
